### ISSUE TITLE
Header toolbar

### ISSUE THREAD

**Issue by TinyWugaga** [TinyWugaga/openai-taking-bot#31]
### Describe the feature or improvement you're requesting

# Expected
- add a Toolbar and the setting functions

### Todo
- [ ]  Switch language (Chinese/English)
- [ ]  Open/Close voice input auto submit
- [ ]  Cookie record conversation/Clear conversation record
    - Leave/Disconnect/Refresh the page
